/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertBox: typeof import('./components/dialogs/AlertBox.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ConfigSavePrompt: typeof import('./components/dialogs/ConfigSavePrompt.vue')['default']
    ConnectToClientDialog: typeof import('./components/dialogs/ConnectToClientDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FadeAndSlideTransitionGroup: typeof import('./components/transitions/FadeAndSlideTransitionGroup.vue')['default']
    GetLiveCompDialog: typeof import('./components/dialogs/GetLiveCompDialog.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('primevue/slider')['default']
    StatusChart: typeof import('./components/StatusChart.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
